<center>
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

#### Add your code below following the instructions given in the course

<h1><center>My Jupyter Notebook on IBM Watson Studio</center></h1>

**Pedro Salvado**
<p>Data Scientist Entry Level</p>

*I am interested in Data Science because it gives me the tools necessary to discover information in data that otherwise would be hidden*


*The prospect of analysing past data to predict future results is very appealing*

###The code below shows a for loop inline to multiply by 2 a list of numbers

In [2]:
list1 = [1, 2, 3, 4, 5, 6]
list2 = [x*2 for x in list1]
list2

[2, 4, 6, 8, 10, 12]

<style>
td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}
</style>

<ol>
  <li> One</li>
  <li> Two</li>
  <li> Three</li>
  <li> Four</li>
</ol>


<table>
  <tr>
    <th><b>Column 1</b></th>
    <th><b>Column 2</b></th>
  <tr>
  <tr>
    <td> (1,1)</td>
    <td> (1,2)</td>
  </tr>
  <tr>
    <td> (2,1)</td>
    <td> (2,2)</td>
  </tr>
  <tr>
    <td> (3,1)</td>
    <td> (3,2)</td>
  </tr>
</table>
<br>

<p><a href="https://www.coursera.org/">Coursera WebSite</a></p>

'x=5'

<code>Python
str = "This is a block level code"
print(str + 'to be shown')
</code>

```Python
str = "This is block level code"
print(str)
```